### ISSUE TITLE
[BUG] Issue handling notes with alphanumeric IDs

### ISSUE THREAD

**Issue by rockstorm101** [ymherklotz/emacs-zettelkasten#11]
I've got an issue with the following line of code. It does not properly handle note IDs starting with a letter like "abc123".
https://github.com/ymherklotz/emacs-zettelkasten/blob/68dc980858ed72f0943fe332c93189dd66b5329c/zettelkasten.el#L100

I've made the following change locally, but I'm unsure it would work for everyone so I thought I would ask before submitting a PR. I don't 100% understand what the `zettelkasten--get-id` function does. I guess it tries to handle note files like "1234-my-note.md" by removing the suffix and the "-my-note" bit. If correct, then the change should work for anyone, if not then I don't fully understand the code, so please bear with me.
```diff
-  (string-match (format "[^0-9]*\\(%s\\)" zettelkasten-id-regexp) note)
+  (string-match (format "^\\(%s\\)" zettelkasten-id-regexp) note)
```
--
Emacs version: 29.3
`zettelkasten` version: 20230108.172
`zettelkasten` configuration:  `zettelkasten-id-regexp "[a-z0-9]+"`

**Comment by ymherklotz** [comment]
Thanks for the report, I think you are right that this was an oversight, and still stems from the time when I had "hardcoded" ids to be only numbers.  I think that your proposed solution is correct, especially with the `^` that was missing in the previous version too.  And your interpretation about what the code should do is correct as well.

Let me know if you want me to make the change or if you want to submit this as a pull request.

**Comment by ymherklotz** [comment]
Btw, I'm glad if the package works for you otherwise and I'm happy to still work on it and implement new features or fix bugs, but I haven't really been adding any new features to it myself since I'm not actively using it myself any more.  I just wanted to note that [denote](https://github.com/protesilaos/denote) is also an excellent package that is newer and has similar goals to this package, just in case you hadn't come across it before.

I do think that `zettelkasten.el` is still simpler and a bit more minimal, so if that fits your need better then that's great!

**Comment by rockstorm101** [comment]
> Btw, I'm glad if the package works for you otherwise and I'm happy to still work on it and implement new features or fix bugs, but I haven't really been adding any new features to it myself since I'm not actively using it myself any more. I just wanted to note that [denote](https://github.com/protesilaos/denote) is also an excellent package that is newer and has similar goals to this package, just in case you hadn't come across it before.
> 
> I do think that `zettelkasten.el` is still simpler and a bit more minimal, so if that fits your need better then that's great!

Thanks a lot for the support and for the alternative suggestion. I'll have a look at it. Though I'm happy with this package to be honest, it does just what I need. So I'm very thankful for your work on this.

**Comment by ymherklotz** [comment]
Great thanks, I've pushed that now and it should be on melpa soon.  Let me know if that works for you.
