### ISSUE TITLE
Opening existing dir with md files - zettelkasten-open-note does not show existing md files

### ISSUE THREAD

**Issue by srustamo** [ymherklotz/emacs-zettelkasten#3]
But it shows the files created with zettelkasten-create-new-note.
Same with zettelkasten-insert-link, existig files are not listed in the minibuffer.

**Comment by ymherklotz** [comment]
What is the format of the filenames? Is it the same as the filenames created by `zettelkasten-create-new-note`?

If they follow the same filename structure (i.e. the ID), then they should appear, as no caching is performed.

Also have you set `zettelkasten-extension` properly to be `.md`?

I originally designed it to only work with `.org`, and have not really tested the `.md` workflow (although it shouldn't be different).  Therefore it would help to get a complete minimal example of what you tried which showed this bug.

**Comment by srustamo** [comment]
I dug a bit into the code and see that it uses RE to make a list of md files. Let me look closer and I'll reopen the issue if still have problems.
