### ISSUE TITLE
Discarded merging of #7 and #8

### ISSUE THREAD

**Issue by tarsius** [ymherklotz/emacs-zettelkasten#9]
**Describe the bug**

You merged #7 and #8 three weeks ago, but a few days ago you discarded those commits. Was that intentional?

**To Reproduce**

```
7278052 * origin/master Add function to update modification time
edba7bc | *   mirror/master Merge pull request #8 from rockstorm101/id-regexp
        | |\  
890ce58 | | * Allow customising ID regexp pattern
        | |/  
        |/|   
a6c8ac8 | * Merge pull request #7 from ymherklotz/custom-id-support
        |/| 
5fa9480 | * Add new function to create custom ID
13f415f | * Update copyright
        |/  
9eb18ec * Prioritise org-zettelkasten
```

**Expected behavior**

Don't rewrite history except maybe to amend a rather recent HEAD.

**Additional context**

I maintain the Emacsmirror and when suspicious history rewriting happens in a mirrored package, then I contact the maintainer.

**Comment by ymherklotz** [comment]
Thanks a lot for this issue, I have merged back the commits now.  I now know to manually merge everytime because github is just a mirror, the history should never be rewritten.

**Comment by tarsius** [comment]
Thanks!
